---
title: "Job Prospects of Fresh Graduates from Universities in Singapore"
---
I decided to dive into researching the job prospects of fresh graduates from Singaporean universities for a few reasons. As a third-year student myself, the looming specter of post-grad life is getting real, and this research is not only interesting but also helps me wrap my head around what's waiting for me after graduation. There's also this perpetual stereotype in Singapore that an individual will be more successful if he/she comes from a certain university or takes certain courses (FASS graduates aren't paid well..?). With the changing job scene in Singapore and the ever-rising cost of living — not to forget the COVID-19 economic downturn — employability is a concern that plagues many soon-to-be-graduates and fresh graduates.

The dataset that I have chosen depicts a Graduate Employment Survey carried out among fresh graduates of local universities from **2013 to 2021**. The dataset can be found here: <https://beta.data.gov.sg/collections/415/view>. It consists of data from

- Nanyang Technological University (NTU)

- National University of Singapore (NUS)

- Singapore Institute of Technology (SIT)

- Singapore Management University (SMU)

- Singapore University of Social Sciences (SUSS)

- Singapore University of Technology and Design (SUTD)

### 1. Is it getting increasingly more difficult for university graduates to get employed?

I first began by finding the total average employment rate by year, across all 6 universities. 

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://nurqistina13.shinyapps.io/personal_app/"> </iframe>
```

Predictably, employment rates of university graduates are high across the years, with values always exceeding 90%. It can be observed that there has been an overall increase in the employment rate over the years. This is notable despite the economic downturn caused by COVID-19. Perhaps this can be attributed to industry trends, where several sectors experiencing growth in Singapore — such as finance, AI, and the green economy — place value on the skills possessed by fresh graduates.

### 2. How has the trend in monthly income evolved over the years?

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://nurqistina13.shinyapps.io/graph_3/"> </iframe>
```

In line with inflation and the rising cost of living in Singapore, average gross monthly income of fresh graduates has increased steadily over the years.

### 3. Does the university matter?
We've all heard that some universities in Singapore are supposedly 'better' than others. This can be influenced by a variety of factors: global and local rankings, programmes offered and infrastructure to name a few. But when it comes to securing a job, does the local university one graduates from actually make a big difference?

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://nurqistina13.shinyapps.io/graph_4/"> </iframe> 
```

The data reveals a positive correlation between Gross Monthly Mean Income and Overall Employment Rate; as one increases, the other tends to rise as well. The data points also tend to aggregate between the income ranges of $3000-$5000 and the employment rates of 80%-100%. This is the case for all universities. 

There are differences in the spread of the data points however, but this could be due to the difference in the number of respondents from each university. Interestingly, contrary to popular belief, universities with a higher global ranking, such as NUS, have a larger spread of employment rate and mean monthly income. 

### 4. Does the degree matter?

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://nurqistina13.shinyapps.io/graph_5/"> </iframe> 
```

